server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=truecharacterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: password

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.echo.springcloud.entities
